apiVersion: apps/v1
kind: CronJob
metadata:
  name: statistics-fetcher
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: statistics-fetcher
            image: mmkorshunova/fetcher:latest
            volumeMounts:
              - name: data-volume
                mountPath: "/statistics-data"
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          volumes:
            - name: data-volume
              hostPath:
                path: /statistics-data
                type: DirectoryOrCreate
