FROM ubuntu:latest

RUN apt-get update -y

RUN apt-get install -y python3-pip python3-dev build-essential python3-flask python3-requests python3-prometheus-client

WORKDIR /app

COPY prometheus_exporter.py /app

EXPOSE 8000

CMD ["python3", "prometheus_exporter.py"]